version: "3.9"

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    ports:
      - "3306:3306"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - keycloak-postgres-network

  keycloak:
    image: jboss/keycloak
    restart: unless-stopped
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    networks:
      - keycloak-postgres-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - keycloak

volumes:
  postgres-data:
  keycloak-data:

networks:
  keycloak-postgres-network:
